# Generated by Django 4.1.7 on 2023-04-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to='recipes/images/'),
        ),
    ]
