# Generated by Django 4.1.7 on 2023-04-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesingredients',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
