# Generated by Django 4.1.7 on 2023-04-22 14:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="hexcolor",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=18,
                samples=[("#FFFFFF", "white"), ("#000000", "black")],
                verbose_name="tag's color",
            ),
        ),
    ]
