# Generated by Django 4.1.7 on 2023-04-22 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_alter_tag_hexcolor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="hexcolor",
            new_name="color",
        ),
    ]
